### ISSUE TITLE
How many peaks should we select when using midas?

### ISSUE THREAD

**Issue by Smilenone** [labomics/midas#11]
Usually, for a scATAC-seq data, I have 1M peaks, and I wonder How many peaks should we select when using midas?

**Comment by zhen-he** [comment]
Please refer to Supplementary Table 13 for the number of peaks for MIDAS as $D^{ATAC}$. I recommend not exceeding 100K peaks to avoid overfitting due to an excessive number of model parameters, especially with fewer cells (e.g., less than 10K). You may consider merging peaks to reduce their number.

**Comment by Smilenone** [comment]
Thanks, and I met a new problem, I got stuck (for more than one hour) when using model.train(), plz see the picture, can you help?
![image](https://github.com/user-attachments/assets/8253e4f4-690d-4d84-afb4-985a73954ce8)

**Comment by JiahaoChow** [comment]
Hi, @Smilenone !

It seems difficult to obtain valid information from the image. Have you successfully run the demo data with the same device? Additionally, please comment out  ``warnings.filterwarnings('ignore')`` to view the warning messages for further diagnosis of the problem.
