### ISSUE TITLE
How to calculate the modality contribution to the final clustering that shown in Fig. 2 (h, i, j)

### ISSUE THREAD

**Issue by ljw-struggle** [labomics/midas#6]
I want to reproduce the plot shown in Fig. 2 (h.i.j), but there are no more details here. Can you provide the code to draw this picture?  thank you very much

Regards,
Jiawei

**Comment by ljw-struggle** [comment]
Your work is inspiring!!! I have learned a lot from this!!!

**Comment by zhen-he** [comment]
Hi, the related code is attached. Please check.

[modal_weights.zip](https://github.com/labomics/midas/files/15137583/modal_weights.zip)
