### ISSUE TITLE
How to integrate RNA+Histone modification data and RNA+ATAC data?

### ISSUE THREAD

**Issue by XiHuYan** [labomics/midas#8]
Hi, I met a problem when applying MIDAS to my own dataset: one batch measured with RNA+histone modafication (H3K27me3) modalities and another batch measured with RNA+ATAC modalities. I defined three modalities as input: rna, atac, and H3K27me3. Following the steps for processing atac data, I split H3K27me3 into chunks by chromosome id. But the code cannot run correctly (I can correctly reproduce the RNA+ATAC integration experiment).  It seems that MIDAS only recognizes chunk inputs for 'atac' modality, although 'H3K27me3' mod is very similar 'atac' mod. On the other hand, taking the H3K27me3 feature (>100,000) as a whole will significantly increase the computational complexity. 

How can I solvle this problem?

**Comment by zhen-he** [comment]
Hello,

Incorporating additional modalities is indeed a fascinating approach. As you may have noticed, in the preprocessing and training sections of the MIDAS code, there is a check to ensure that the modalities belong to the set {ATAC, RNA, ADT}. I recommend thoroughly understanding the code as this will not only guide you on how to modify it, but also significantly reduce the chances of encountering bugs that may not trigger errors yet lead to logical inconsistencies.

Regarding the H3K27me3 feature, although I am not deeply familiar with it, there are several strategies you might consider to reduce computational complexity:
1. Apply feature selection to eliminate redundant features.
2. Increase the use of local connections (if feasible) to decrease the number of model parameters. For instance, you could divide each chromosome into smaller segments.
3. Replace fully connected layers with 1D convolutional layers to further reduce the number of model parameters.
4. Pretrain the H3K27me3 features using architectures similar to autoencoders. For example, you could initially train an autoencoder to reduce the dimensionality of the H3K27me3 features, then freeze both the encoder and decoder of this autoencoder. Subsequently, integrate them into MIDAS’s input and reconstruction layers respectively.

**Comment by XiHuYan** [comment]
Thanks a lot. I will follow you suggestions.
