### ISSUE TITLE
Allowing peaks in chrX and chrY

### ISSUE THREAD

**Issue by sshen82** [labomics/midas#9]
Hi, thank you for this great package! I encounted a bug "ValueError: invalid literal for int() with base 10: 'X'" when my peak list contains peaks from "chrX" and "chrY". Those peaks are neglectable, but I guess those peaks are sometimes important for other cases, so you might consider allowing those peaks.

**Comment by JiahaoChow** [comment]
Thank you for your question! 

This issue can be resolved by removing the **_int()_** from _**scmidas.utils.sort_chromosomes()**_. 

The modified function has passed tests, and the _feat_dims.csv_ file generated using this function is normal, as well as the model's _n_chr_ is correct, and the _model.train()_ part runs normally. However, we have not conducted comprehensive testing, so we cannot guarantee the correctness of the integrated results. We welcome your continued feedback! We will push the modified content to PyPI subsequently!

**Comment by JiahaoChow** [comment]
Sorry, we found that removing int() directly leads to an incorrect feat_dims.csv, which will cause the feature dimensions to be organized in the order of '1', '10' instead of '1', '2'. We suggest removing the sorting part. Make sure your input is organized by chromosomes.

Modify your code at scmidas.datasets from line 332:
```
for m in utils.ref_sort(feat_names.keys(), ['atac', 'rna', 'adt']):
    if m=="atac":
        chr_dims = []
        split_chr = utils.split_list_by_prefix(feat_names["atac"])
        for c in split_chr.keys():
            chr_dims.append(len(split_chr[c]))
        feat_dims[m] = chr_dims
    else:
        if "atac" in feat_names:
            feat_dims[m] = [len(feat_names[m])] * len(split_chr.keys()) # All columns in the pandas DataFrame must have uniform dimensions.

        else:
            feat_dims[m] = [len(feat_names[m])]
```

**Comment by sshen82** [comment]
Get it! Thank you for continue looking into it! My current workaround is just removing those chrX and Y peaks, since there are only 10 of them.
